### ISSUE TITLE
Exception: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by damian123** [gomons/CppRpcLight#1]
Thank you for an awesome project!

When I close the client I get this error:
Exception: An existing connection was forcibly closed by the remote host

Is it possible to keep the server alive and wait for the next client to connect?

The same when I kill the server the client core dumps

**Comment by gomons** [comment]
Hello, Damian!

Yes, it is possible. I will check it and fix in a few days. Thank you for your interest and report!

**Comment by gomons** [comment]
As a workaround I can propose to handle exceptions that io_service propogate in main.cpp files for client and server:
```
// RpcServer/main.cpp
while (!stop_condition)
{
    try {
        io_service.run();
    } catch(const std::exception &e) {
        std::cout << "Error: " << e.what() << std::endl;
        io_service.reset();
    }
}
```
I will think how to change exception handling mechanism in more convinient way.
